name: Build Aseprite Windows
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - principal

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          choco install ninja
          pip install urllib3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Download and Extract Skia
        shell: powershell
        run: |
          $url = "https://github.com/aseprite/skia/releases/download/m102-861e47433b/Skia-Windows-Release-x64.zip"
          # Forzamos el uso de TLS 1.2 para evitar problemas de conexión
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Write-Host "Descargando Skia desde $url"
          Invoke-WebRequest -Uri $url -OutFile skia.zip -UserAgent "Mozilla/5.0"
          Write-Host "Extrayendo..."
          Expand-Archive -Path skia.zip -DestinationPath skia
          Remove-Item skia.zip

      - name: Configure and Compile
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=../skia -DSKIA_LIBRARY_DIR=../skia/out/Release-x64 ..
          ninja aseprite

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Bundle
          path: build/bin/
